// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0
// 	protoc        v3.11.4
// source: groupbirthday.proto

package contract

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type GetGroupsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MemberId int32 `protobuf:"varint,1,opt,name=memberId,proto3" json:"memberId,omitempty"`
}

func (x *GetGroupsRequest) Reset() {
	*x = GetGroupsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_groupbirthday_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupsRequest) ProtoMessage() {}

func (x *GetGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_groupbirthday_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupsRequest.ProtoReflect.Descriptor instead.
func (*GetGroupsRequest) Descriptor() ([]byte, []int) {
	return file_groupbirthday_proto_rawDescGZIP(), []int{0}
}

func (x *GetGroupsRequest) GetMemberId() int32 {
	if x != nil {
		return x.MemberId
	}
	return 0
}

type GetGroupsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Groups []string `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
}

func (x *GetGroupsReply) Reset() {
	*x = GetGroupsReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_groupbirthday_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGroupsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupsReply) ProtoMessage() {}

func (x *GetGroupsReply) ProtoReflect() protoreflect.Message {
	mi := &file_groupbirthday_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupsReply.ProtoReflect.Descriptor instead.
func (*GetGroupsReply) Descriptor() ([]byte, []int) {
	return file_groupbirthday_proto_rawDescGZIP(), []int{1}
}

func (x *GetGroupsReply) GetGroups() []string {
	if x != nil {
		return x.Groups
	}
	return nil
}

type GetMemberIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FirstName        string `protobuf:"bytes,1,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName         string `protobuf:"bytes,2,opt,name=lastName,proto3" json:"lastName,omitempty"`
	TelegramUsername string `protobuf:"bytes,3,opt,name=telegramUsername,proto3" json:"telegramUsername,omitempty"`
}

func (x *GetMemberIdRequest) Reset() {
	*x = GetMemberIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_groupbirthday_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMemberIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMemberIdRequest) ProtoMessage() {}

func (x *GetMemberIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_groupbirthday_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMemberIdRequest.ProtoReflect.Descriptor instead.
func (*GetMemberIdRequest) Descriptor() ([]byte, []int) {
	return file_groupbirthday_proto_rawDescGZIP(), []int{2}
}

func (x *GetMemberIdRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *GetMemberIdRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *GetMemberIdRequest) GetTelegramUsername() string {
	if x != nil {
		return x.TelegramUsername
	}
	return ""
}

type GetMemberIdReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MemberId int32 `protobuf:"varint,1,opt,name=memberId,proto3" json:"memberId,omitempty"`
}

func (x *GetMemberIdReply) Reset() {
	*x = GetMemberIdReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_groupbirthday_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMemberIdReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMemberIdReply) ProtoMessage() {}

func (x *GetMemberIdReply) ProtoReflect() protoreflect.Message {
	mi := &file_groupbirthday_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMemberIdReply.ProtoReflect.Descriptor instead.
func (*GetMemberIdReply) Descriptor() ([]byte, []int) {
	return file_groupbirthday_proto_rawDescGZIP(), []int{3}
}

func (x *GetMemberIdReply) GetMemberId() int32 {
	if x != nil {
		return x.MemberId
	}
	return 0
}

type GetMemberBirthdaysRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupName string `protobuf:"bytes,1,opt,name=groupName,proto3" json:"groupName,omitempty"`
}

func (x *GetMemberBirthdaysRequest) Reset() {
	*x = GetMemberBirthdaysRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_groupbirthday_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMemberBirthdaysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMemberBirthdaysRequest) ProtoMessage() {}

func (x *GetMemberBirthdaysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_groupbirthday_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMemberBirthdaysRequest.ProtoReflect.Descriptor instead.
func (*GetMemberBirthdaysRequest) Descriptor() ([]byte, []int) {
	return file_groupbirthday_proto_rawDescGZIP(), []int{4}
}

func (x *GetMemberBirthdaysRequest) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

type GetMemberBirthdaysReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MemberBirthdays []*MemberBirthday `protobuf:"bytes,1,rep,name=memberBirthdays,proto3" json:"memberBirthdays,omitempty"`
}

func (x *GetMemberBirthdaysReply) Reset() {
	*x = GetMemberBirthdaysReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_groupbirthday_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMemberBirthdaysReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMemberBirthdaysReply) ProtoMessage() {}

func (x *GetMemberBirthdaysReply) ProtoReflect() protoreflect.Message {
	mi := &file_groupbirthday_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMemberBirthdaysReply.ProtoReflect.Descriptor instead.
func (*GetMemberBirthdaysReply) Descriptor() ([]byte, []int) {
	return file_groupbirthday_proto_rawDescGZIP(), []int{5}
}

func (x *GetMemberBirthdaysReply) GetMemberBirthdays() []*MemberBirthday {
	if x != nil {
		return x.MemberBirthdays
	}
	return nil
}

type MemberBirthday struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FirstName string `protobuf:"bytes,1,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName  string `protobuf:"bytes,2,opt,name=lastName,proto3" json:"lastName,omitempty"`
	Day       int32  `protobuf:"varint,3,opt,name=day,proto3" json:"day,omitempty"`
	Month     int32  `protobuf:"varint,4,opt,name=month,proto3" json:"month,omitempty"`
}

func (x *MemberBirthday) Reset() {
	*x = MemberBirthday{}
	if protoimpl.UnsafeEnabled {
		mi := &file_groupbirthday_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MemberBirthday) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberBirthday) ProtoMessage() {}

func (x *MemberBirthday) ProtoReflect() protoreflect.Message {
	mi := &file_groupbirthday_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberBirthday.ProtoReflect.Descriptor instead.
func (*MemberBirthday) Descriptor() ([]byte, []int) {
	return file_groupbirthday_proto_rawDescGZIP(), []int{6}
}

func (x *MemberBirthday) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *MemberBirthday) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *MemberBirthday) GetDay() int32 {
	if x != nil {
		return x.Day
	}
	return 0
}

func (x *MemberBirthday) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

type SaveMemberRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FirstName        string `protobuf:"bytes,1,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName         string `protobuf:"bytes,2,opt,name=lastName,proto3" json:"lastName,omitempty"`
	TelegramUsername string `protobuf:"bytes,3,opt,name=telegramUsername,proto3" json:"telegramUsername,omitempty"`
	TelegramUserId   int32  `protobuf:"varint,4,opt,name=telegramUserId,proto3" json:"telegramUserId,omitempty"`
	TelegramChatId   int64  `protobuf:"varint,5,opt,name=telegramChatId,proto3" json:"telegramChatId,omitempty"`
	TelegramChatName string `protobuf:"bytes,6,opt,name=telegramChatName,proto3" json:"telegramChatName,omitempty"`
}

func (x *SaveMemberRequest) Reset() {
	*x = SaveMemberRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_groupbirthday_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveMemberRequest) ProtoMessage() {}

func (x *SaveMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_groupbirthday_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveMemberRequest.ProtoReflect.Descriptor instead.
func (*SaveMemberRequest) Descriptor() ([]byte, []int) {
	return file_groupbirthday_proto_rawDescGZIP(), []int{7}
}

func (x *SaveMemberRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *SaveMemberRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *SaveMemberRequest) GetTelegramUsername() string {
	if x != nil {
		return x.TelegramUsername
	}
	return ""
}

func (x *SaveMemberRequest) GetTelegramUserId() int32 {
	if x != nil {
		return x.TelegramUserId
	}
	return 0
}

func (x *SaveMemberRequest) GetTelegramChatId() int64 {
	if x != nil {
		return x.TelegramChatId
	}
	return 0
}

func (x *SaveMemberRequest) GetTelegramChatName() string {
	if x != nil {
		return x.TelegramChatName
	}
	return ""
}

type SaveMemberReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MemberId int32 `protobuf:"varint,1,opt,name=memberId,proto3" json:"memberId,omitempty"`
}

func (x *SaveMemberReply) Reset() {
	*x = SaveMemberReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_groupbirthday_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveMemberReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveMemberReply) ProtoMessage() {}

func (x *SaveMemberReply) ProtoReflect() protoreflect.Message {
	mi := &file_groupbirthday_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveMemberReply.ProtoReflect.Descriptor instead.
func (*SaveMemberReply) Descriptor() ([]byte, []int) {
	return file_groupbirthday_proto_rawDescGZIP(), []int{8}
}

func (x *SaveMemberReply) GetMemberId() int32 {
	if x != nil {
		return x.MemberId
	}
	return 0
}

var File_groupbirthday_proto protoreflect.FileDescriptor

var file_groupbirthday_proto_rawDesc = []byte{
	0x0a, 0x13, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x62, 0x69, 0x72, 0x74, 0x68, 0x64, 0x61, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x22,
	0x2e, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x49, 0x64, 0x22,
	0x28, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x06, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x22, 0x7a, 0x0a, 0x12, 0x47, 0x65, 0x74,
	0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1c, 0x0a, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x6c, 0x61, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x6c, 0x61, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x2a, 0x0a, 0x10, 0x74, 0x65, 0x6c,
	0x65, 0x67, 0x72, 0x61, 0x6d, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x10, 0x74, 0x65, 0x6c, 0x65, 0x67, 0x72, 0x61, 0x6d, 0x55, 0x73, 0x65,
	0x72, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x2e, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x49, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x6d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x49, 0x64, 0x22, 0x39, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x42, 0x69, 0x72, 0x74, 0x68, 0x64, 0x61, 0x79, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x4e, 0x61, 0x6d, 0x65,
	0x22, 0x5d, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x42, 0x69, 0x72,
	0x74, 0x68, 0x64, 0x61, 0x79, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x42, 0x0a, 0x0f, 0x6d,
	0x65, 0x6d, 0x62, 0x65, 0x72, 0x42, 0x69, 0x72, 0x74, 0x68, 0x64, 0x61, 0x79, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e,
	0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x42, 0x69, 0x72, 0x74, 0x68, 0x64, 0x61, 0x79, 0x52, 0x0f,
	0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x42, 0x69, 0x72, 0x74, 0x68, 0x64, 0x61, 0x79, 0x73, 0x22,
	0x72, 0x0a, 0x0e, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x42, 0x69, 0x72, 0x74, 0x68, 0x64, 0x61,
	0x79, 0x12, 0x1c, 0x0a, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x64,
	0x61, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x64, 0x61, 0x79, 0x12, 0x14, 0x0a,
	0x05, 0x6d, 0x6f, 0x6e, 0x74, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6d, 0x6f,
	0x6e, 0x74, 0x68, 0x22, 0xf5, 0x01, 0x0a, 0x11, 0x53, 0x61, 0x76, 0x65, 0x4d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x66, 0x69, 0x72,
	0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x69,
	0x72, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x2a, 0x0a, 0x10, 0x74, 0x65, 0x6c, 0x65, 0x67, 0x72, 0x61, 0x6d, 0x55,
	0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x74,
	0x65, 0x6c, 0x65, 0x67, 0x72, 0x61, 0x6d, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x26, 0x0a, 0x0e, 0x74, 0x65, 0x6c, 0x65, 0x67, 0x72, 0x61, 0x6d, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x74, 0x65, 0x6c, 0x65, 0x67, 0x72, 0x61,
	0x6d, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x0e, 0x74, 0x65, 0x6c, 0x65, 0x67,
	0x72, 0x61, 0x6d, 0x43, 0x68, 0x61, 0x74, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0e, 0x74, 0x65, 0x6c, 0x65, 0x67, 0x72, 0x61, 0x6d, 0x43, 0x68, 0x61, 0x74, 0x49, 0x64, 0x12,
	0x2a, 0x0a, 0x10, 0x74, 0x65, 0x6c, 0x65, 0x67, 0x72, 0x61, 0x6d, 0x43, 0x68, 0x61, 0x74, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x74, 0x65, 0x6c, 0x65, 0x67,
	0x72, 0x61, 0x6d, 0x43, 0x68, 0x61, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x2d, 0x0a, 0x0f, 0x53,
	0x61, 0x76, 0x65, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1a,
	0x0a, 0x08, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x08, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x49, 0x64, 0x32, 0xc7, 0x02, 0x0a, 0x0d, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x42, 0x69, 0x72, 0x74, 0x68, 0x64, 0x61, 0x79, 0x12, 0x43, 0x0a, 0x09,
	0x47, 0x65, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x12, 0x1a, 0x2e, 0x63, 0x6f, 0x6e, 0x74,
	0x72, 0x61, 0x63, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74,
	0x2e, 0x47, 0x65, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22,
	0x00, 0x12, 0x49, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x1c, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x4d,
	0x65, 0x6d, 0x62, 0x65, 0x72, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a,
	0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x49, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x5e, 0x0a, 0x12,
	0x47, 0x65, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x42, 0x69, 0x72, 0x74, 0x68, 0x64, 0x61,
	0x79, 0x73, 0x12, 0x23, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x47, 0x65,
	0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x42, 0x69, 0x72, 0x74, 0x68, 0x64, 0x61, 0x79, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61,
	0x63, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x42, 0x69, 0x72, 0x74,
	0x68, 0x64, 0x61, 0x79, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x46, 0x0a, 0x0a,
	0x53, 0x61, 0x76, 0x65, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x1b, 0x2e, 0x63, 0x6f, 0x6e,
	0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x53, 0x61, 0x76, 0x65, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61,
	0x63, 0x74, 0x2e, 0x53, 0x61, 0x76, 0x65, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x22, 0x00, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x3b, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61,
	0x63, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_groupbirthday_proto_rawDescOnce sync.Once
	file_groupbirthday_proto_rawDescData = file_groupbirthday_proto_rawDesc
)

func file_groupbirthday_proto_rawDescGZIP() []byte {
	file_groupbirthday_proto_rawDescOnce.Do(func() {
		file_groupbirthday_proto_rawDescData = protoimpl.X.CompressGZIP(file_groupbirthday_proto_rawDescData)
	})
	return file_groupbirthday_proto_rawDescData
}

var file_groupbirthday_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_groupbirthday_proto_goTypes = []interface{}{
	(*GetGroupsRequest)(nil),          // 0: contract.GetGroupsRequest
	(*GetGroupsReply)(nil),            // 1: contract.GetGroupsReply
	(*GetMemberIdRequest)(nil),        // 2: contract.GetMemberIdRequest
	(*GetMemberIdReply)(nil),          // 3: contract.GetMemberIdReply
	(*GetMemberBirthdaysRequest)(nil), // 4: contract.GetMemberBirthdaysRequest
	(*GetMemberBirthdaysReply)(nil),   // 5: contract.GetMemberBirthdaysReply
	(*MemberBirthday)(nil),            // 6: contract.MemberBirthday
	(*SaveMemberRequest)(nil),         // 7: contract.SaveMemberRequest
	(*SaveMemberReply)(nil),           // 8: contract.SaveMemberReply
}
var file_groupbirthday_proto_depIdxs = []int32{
	6, // 0: contract.GetMemberBirthdaysReply.memberBirthdays:type_name -> contract.MemberBirthday
	0, // 1: contract.GroupBirthday.GetGroups:input_type -> contract.GetGroupsRequest
	2, // 2: contract.GroupBirthday.GetMemberId:input_type -> contract.GetMemberIdRequest
	4, // 3: contract.GroupBirthday.GetMemberBirthdays:input_type -> contract.GetMemberBirthdaysRequest
	7, // 4: contract.GroupBirthday.SaveMember:input_type -> contract.SaveMemberRequest
	1, // 5: contract.GroupBirthday.GetGroups:output_type -> contract.GetGroupsReply
	3, // 6: contract.GroupBirthday.GetMemberId:output_type -> contract.GetMemberIdReply
	5, // 7: contract.GroupBirthday.GetMemberBirthdays:output_type -> contract.GetMemberBirthdaysReply
	8, // 8: contract.GroupBirthday.SaveMember:output_type -> contract.SaveMemberReply
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_groupbirthday_proto_init() }
func file_groupbirthday_proto_init() {
	if File_groupbirthday_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_groupbirthday_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGroupsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_groupbirthday_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGroupsReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_groupbirthday_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMemberIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_groupbirthday_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMemberIdReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_groupbirthday_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMemberBirthdaysRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_groupbirthday_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMemberBirthdaysReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_groupbirthday_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MemberBirthday); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_groupbirthday_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveMemberRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_groupbirthday_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveMemberReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_groupbirthday_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_groupbirthday_proto_goTypes,
		DependencyIndexes: file_groupbirthday_proto_depIdxs,
		MessageInfos:      file_groupbirthday_proto_msgTypes,
	}.Build()
	File_groupbirthday_proto = out.File
	file_groupbirthday_proto_rawDesc = nil
	file_groupbirthday_proto_goTypes = nil
	file_groupbirthday_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// GroupBirthdayClient is the client API for GroupBirthday service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GroupBirthdayClient interface {
	GetGroups(ctx context.Context, in *GetGroupsRequest, opts ...grpc.CallOption) (*GetGroupsReply, error)
	GetMemberId(ctx context.Context, in *GetMemberIdRequest, opts ...grpc.CallOption) (*GetMemberIdReply, error)
	GetMemberBirthdays(ctx context.Context, in *GetMemberBirthdaysRequest, opts ...grpc.CallOption) (*GetMemberBirthdaysReply, error)
	SaveMember(ctx context.Context, in *SaveMemberRequest, opts ...grpc.CallOption) (*SaveMemberReply, error)
}

type groupBirthdayClient struct {
	cc grpc.ClientConnInterface
}

func NewGroupBirthdayClient(cc grpc.ClientConnInterface) GroupBirthdayClient {
	return &groupBirthdayClient{cc}
}

func (c *groupBirthdayClient) GetGroups(ctx context.Context, in *GetGroupsRequest, opts ...grpc.CallOption) (*GetGroupsReply, error) {
	out := new(GetGroupsReply)
	err := c.cc.Invoke(ctx, "/contract.GroupBirthday/GetGroups", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupBirthdayClient) GetMemberId(ctx context.Context, in *GetMemberIdRequest, opts ...grpc.CallOption) (*GetMemberIdReply, error) {
	out := new(GetMemberIdReply)
	err := c.cc.Invoke(ctx, "/contract.GroupBirthday/GetMemberId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupBirthdayClient) GetMemberBirthdays(ctx context.Context, in *GetMemberBirthdaysRequest, opts ...grpc.CallOption) (*GetMemberBirthdaysReply, error) {
	out := new(GetMemberBirthdaysReply)
	err := c.cc.Invoke(ctx, "/contract.GroupBirthday/GetMemberBirthdays", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupBirthdayClient) SaveMember(ctx context.Context, in *SaveMemberRequest, opts ...grpc.CallOption) (*SaveMemberReply, error) {
	out := new(SaveMemberReply)
	err := c.cc.Invoke(ctx, "/contract.GroupBirthday/SaveMember", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GroupBirthdayServer is the server API for GroupBirthday service.
type GroupBirthdayServer interface {
	GetGroups(context.Context, *GetGroupsRequest) (*GetGroupsReply, error)
	GetMemberId(context.Context, *GetMemberIdRequest) (*GetMemberIdReply, error)
	GetMemberBirthdays(context.Context, *GetMemberBirthdaysRequest) (*GetMemberBirthdaysReply, error)
	SaveMember(context.Context, *SaveMemberRequest) (*SaveMemberReply, error)
}

// UnimplementedGroupBirthdayServer can be embedded to have forward compatible implementations.
type UnimplementedGroupBirthdayServer struct {
}

func (*UnimplementedGroupBirthdayServer) GetGroups(context.Context, *GetGroupsRequest) (*GetGroupsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGroups not implemented")
}
func (*UnimplementedGroupBirthdayServer) GetMemberId(context.Context, *GetMemberIdRequest) (*GetMemberIdReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMemberId not implemented")
}
func (*UnimplementedGroupBirthdayServer) GetMemberBirthdays(context.Context, *GetMemberBirthdaysRequest) (*GetMemberBirthdaysReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMemberBirthdays not implemented")
}
func (*UnimplementedGroupBirthdayServer) SaveMember(context.Context, *SaveMemberRequest) (*SaveMemberReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveMember not implemented")
}

func RegisterGroupBirthdayServer(s *grpc.Server, srv GroupBirthdayServer) {
	s.RegisterService(&_GroupBirthday_serviceDesc, srv)
}

func _GroupBirthday_GetGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGroupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupBirthdayServer).GetGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/contract.GroupBirthday/GetGroups",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupBirthdayServer).GetGroups(ctx, req.(*GetGroupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupBirthday_GetMemberId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMemberIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupBirthdayServer).GetMemberId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/contract.GroupBirthday/GetMemberId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupBirthdayServer).GetMemberId(ctx, req.(*GetMemberIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupBirthday_GetMemberBirthdays_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMemberBirthdaysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupBirthdayServer).GetMemberBirthdays(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/contract.GroupBirthday/GetMemberBirthdays",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupBirthdayServer).GetMemberBirthdays(ctx, req.(*GetMemberBirthdaysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupBirthday_SaveMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupBirthdayServer).SaveMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/contract.GroupBirthday/SaveMember",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupBirthdayServer).SaveMember(ctx, req.(*SaveMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GroupBirthday_serviceDesc = grpc.ServiceDesc{
	ServiceName: "contract.GroupBirthday",
	HandlerType: (*GroupBirthdayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetGroups",
			Handler:    _GroupBirthday_GetGroups_Handler,
		},
		{
			MethodName: "GetMemberId",
			Handler:    _GroupBirthday_GetMemberId_Handler,
		},
		{
			MethodName: "GetMemberBirthdays",
			Handler:    _GroupBirthday_GetMemberBirthdays_Handler,
		},
		{
			MethodName: "SaveMember",
			Handler:    _GroupBirthday_SaveMember_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "groupbirthday.proto",
}
