// Code generated by protoc-gen-go. DO NOT EDIT.
// source: groupbirthday.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetGroupsRequest struct {
	MemberId             int32    `protobuf:"varint,1,opt,name=memberId,proto3" json:"memberId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetGroupsRequest) Reset()         { *m = GetGroupsRequest{} }
func (m *GetGroupsRequest) String() string { return proto.CompactTextString(m) }
func (*GetGroupsRequest) ProtoMessage()    {}
func (*GetGroupsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_203a0210451df990, []int{0}
}

func (m *GetGroupsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGroupsRequest.Unmarshal(m, b)
}
func (m *GetGroupsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGroupsRequest.Marshal(b, m, deterministic)
}
func (m *GetGroupsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGroupsRequest.Merge(m, src)
}
func (m *GetGroupsRequest) XXX_Size() int {
	return xxx_messageInfo_GetGroupsRequest.Size(m)
}
func (m *GetGroupsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGroupsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetGroupsRequest proto.InternalMessageInfo

func (m *GetGroupsRequest) GetMemberId() int32 {
	if m != nil {
		return m.MemberId
	}
	return 0
}

type GetGroupsReply struct {
	Groups               []string `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetGroupsReply) Reset()         { *m = GetGroupsReply{} }
func (m *GetGroupsReply) String() string { return proto.CompactTextString(m) }
func (*GetGroupsReply) ProtoMessage()    {}
func (*GetGroupsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_203a0210451df990, []int{1}
}

func (m *GetGroupsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGroupsReply.Unmarshal(m, b)
}
func (m *GetGroupsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGroupsReply.Marshal(b, m, deterministic)
}
func (m *GetGroupsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGroupsReply.Merge(m, src)
}
func (m *GetGroupsReply) XXX_Size() int {
	return xxx_messageInfo_GetGroupsReply.Size(m)
}
func (m *GetGroupsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGroupsReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetGroupsReply proto.InternalMessageInfo

func (m *GetGroupsReply) GetGroups() []string {
	if m != nil {
		return m.Groups
	}
	return nil
}

type GetMemberIdRequest struct {
	FirstName            string   `protobuf:"bytes,1,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName             string   `protobuf:"bytes,2,opt,name=lastName,proto3" json:"lastName,omitempty"`
	TelegramUsername     string   `protobuf:"bytes,3,opt,name=telegramUsername,proto3" json:"telegramUsername,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMemberIdRequest) Reset()         { *m = GetMemberIdRequest{} }
func (m *GetMemberIdRequest) String() string { return proto.CompactTextString(m) }
func (*GetMemberIdRequest) ProtoMessage()    {}
func (*GetMemberIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_203a0210451df990, []int{2}
}

func (m *GetMemberIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMemberIdRequest.Unmarshal(m, b)
}
func (m *GetMemberIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMemberIdRequest.Marshal(b, m, deterministic)
}
func (m *GetMemberIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMemberIdRequest.Merge(m, src)
}
func (m *GetMemberIdRequest) XXX_Size() int {
	return xxx_messageInfo_GetMemberIdRequest.Size(m)
}
func (m *GetMemberIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMemberIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMemberIdRequest proto.InternalMessageInfo

func (m *GetMemberIdRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *GetMemberIdRequest) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *GetMemberIdRequest) GetTelegramUsername() string {
	if m != nil {
		return m.TelegramUsername
	}
	return ""
}

type GetMemberIdReply struct {
	MemberId             int32    `protobuf:"varint,1,opt,name=memberId,proto3" json:"memberId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMemberIdReply) Reset()         { *m = GetMemberIdReply{} }
func (m *GetMemberIdReply) String() string { return proto.CompactTextString(m) }
func (*GetMemberIdReply) ProtoMessage()    {}
func (*GetMemberIdReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_203a0210451df990, []int{3}
}

func (m *GetMemberIdReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMemberIdReply.Unmarshal(m, b)
}
func (m *GetMemberIdReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMemberIdReply.Marshal(b, m, deterministic)
}
func (m *GetMemberIdReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMemberIdReply.Merge(m, src)
}
func (m *GetMemberIdReply) XXX_Size() int {
	return xxx_messageInfo_GetMemberIdReply.Size(m)
}
func (m *GetMemberIdReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMemberIdReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetMemberIdReply proto.InternalMessageInfo

func (m *GetMemberIdReply) GetMemberId() int32 {
	if m != nil {
		return m.MemberId
	}
	return 0
}

func init() {
	proto.RegisterType((*GetGroupsRequest)(nil), "GetGroupsRequest")
	proto.RegisterType((*GetGroupsReply)(nil), "GetGroupsReply")
	proto.RegisterType((*GetMemberIdRequest)(nil), "GetMemberIdRequest")
	proto.RegisterType((*GetMemberIdReply)(nil), "GetMemberIdReply")
}

func init() { proto.RegisterFile("groupbirthday.proto", fileDescriptor_203a0210451df990) }

var fileDescriptor_203a0210451df990 = []byte{
	// 236 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4e, 0x2f, 0xca, 0x2f,
	0x2d, 0x48, 0xca, 0x2c, 0x2a, 0xc9, 0x48, 0x49, 0xac, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57,
	0xd2, 0xe3, 0x12, 0x70, 0x4f, 0x2d, 0x71, 0x07, 0xc9, 0x14, 0x07, 0xa5, 0x16, 0x96, 0xa6, 0x16,
	0x97, 0x08, 0x49, 0x71, 0x71, 0xe4, 0xa6, 0xe6, 0x26, 0xa5, 0x16, 0x79, 0xa6, 0x48, 0x30, 0x2a,
	0x30, 0x6a, 0xb0, 0x06, 0xc1, 0xf9, 0x4a, 0x1a, 0x5c, 0x7c, 0x48, 0xea, 0x0b, 0x72, 0x2a, 0x85,
	0xc4, 0xb8, 0xd8, 0xc0, 0x06, 0x17, 0x4b, 0x30, 0x2a, 0x30, 0x6b, 0x70, 0x06, 0x41, 0x79, 0x4a,
	0x55, 0x5c, 0x42, 0xee, 0xa9, 0x25, 0xbe, 0x50, 0x8d, 0x30, 0xb3, 0x65, 0xb8, 0x38, 0xd3, 0x32,
	0x8b, 0x8a, 0x4b, 0xfc, 0x12, 0x73, 0x53, 0xc1, 0x86, 0x73, 0x06, 0x21, 0x04, 0x40, 0x36, 0xe7,
	0x24, 0x42, 0x25, 0x99, 0xc0, 0x92, 0x70, 0xbe, 0x90, 0x16, 0x97, 0x40, 0x49, 0x6a, 0x4e, 0x6a,
	0x7a, 0x51, 0x62, 0x6e, 0x68, 0x71, 0x6a, 0x51, 0x1e, 0x48, 0x0d, 0x33, 0x58, 0x0d, 0x86, 0x38,
	0xd4, 0x57, 0x08, 0xbb, 0x41, 0xee, 0xc4, 0xe3, 0x2b, 0xa3, 0x6a, 0x2e, 0x5e, 0xb0, 0x97, 0x9c,
	0xa0, 0x81, 0x23, 0x64, 0xc8, 0xc5, 0x09, 0xf7, 0xa6, 0x90, 0xa0, 0x1e, 0x7a, 0x10, 0x49, 0xf1,
	0xeb, 0xa1, 0x86, 0x82, 0x12, 0x83, 0x90, 0x39, 0x17, 0x37, 0x92, 0x9d, 0x42, 0xc2, 0x7a, 0x98,
	0xbe, 0x97, 0x12, 0xd4, 0x43, 0x77, 0x96, 0x12, 0x43, 0x12, 0x1b, 0x38, 0x26, 0x8c, 0x01, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x63, 0x58, 0x8d, 0x07, 0xa0, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GroupBirthdayClient is the client API for GroupBirthday service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GroupBirthdayClient interface {
	GetGroups(ctx context.Context, in *GetGroupsRequest, opts ...grpc.CallOption) (*GetGroupsReply, error)
	GetMemberId(ctx context.Context, in *GetMemberIdRequest, opts ...grpc.CallOption) (*GetMemberIdReply, error)
}

type groupBirthdayClient struct {
	cc *grpc.ClientConn
}

func NewGroupBirthdayClient(cc *grpc.ClientConn) GroupBirthdayClient {
	return &groupBirthdayClient{cc}
}

func (c *groupBirthdayClient) GetGroups(ctx context.Context, in *GetGroupsRequest, opts ...grpc.CallOption) (*GetGroupsReply, error) {
	out := new(GetGroupsReply)
	err := c.cc.Invoke(ctx, "/GroupBirthday/GetGroups", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupBirthdayClient) GetMemberId(ctx context.Context, in *GetMemberIdRequest, opts ...grpc.CallOption) (*GetMemberIdReply, error) {
	out := new(GetMemberIdReply)
	err := c.cc.Invoke(ctx, "/GroupBirthday/GetMemberId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GroupBirthdayServer is the server API for GroupBirthday service.
type GroupBirthdayServer interface {
	GetGroups(context.Context, *GetGroupsRequest) (*GetGroupsReply, error)
	GetMemberId(context.Context, *GetMemberIdRequest) (*GetMemberIdReply, error)
}

// UnimplementedGroupBirthdayServer can be embedded to have forward compatible implementations.
type UnimplementedGroupBirthdayServer struct {
}

func (*UnimplementedGroupBirthdayServer) GetGroups(ctx context.Context, req *GetGroupsRequest) (*GetGroupsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGroups not implemented")
}
func (*UnimplementedGroupBirthdayServer) GetMemberId(ctx context.Context, req *GetMemberIdRequest) (*GetMemberIdReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMemberId not implemented")
}

func RegisterGroupBirthdayServer(s *grpc.Server, srv GroupBirthdayServer) {
	s.RegisterService(&_GroupBirthday_serviceDesc, srv)
}

func _GroupBirthday_GetGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGroupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupBirthdayServer).GetGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GroupBirthday/GetGroups",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupBirthdayServer).GetGroups(ctx, req.(*GetGroupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupBirthday_GetMemberId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMemberIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupBirthdayServer).GetMemberId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GroupBirthday/GetMemberId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupBirthdayServer).GetMemberId(ctx, req.(*GetMemberIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GroupBirthday_serviceDesc = grpc.ServiceDesc{
	ServiceName: "GroupBirthday",
	HandlerType: (*GroupBirthdayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetGroups",
			Handler:    _GroupBirthday_GetGroups_Handler,
		},
		{
			MethodName: "GetMemberId",
			Handler:    _GroupBirthday_GetMemberId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "groupbirthday.proto",
}
